### ISSUE TITLE
Chai AssertionError for emit withArgs(nestedStruct)

### ISSUE THREAD

**Issue by gitpusha** [TrueFiEng/Waffle#245]
Hi,

Env:
- ethers@4.0.47
- ethereum-waffle@2.4.1

Solidity:
```solidity
struct Task {
    address foo;
    uint256 next; 
    address[] bar;  
}

struct TaskReceipt {
    uint256 id;
    address userProxy;
    Task task;
}
```

I get this errror when trying to listen to the emission of **TaskReceipt** via
```
....
to.emit(contract, "LogTaskSubmitted").withArgs(taskReceiptStruct);
```

Error: 
`AssertionError: expected { Object (id, userProxy, ...) } to equal [ Array(3) ]`

**I assume this error is because of the way ethers v4 4.0.47 represents nested structs.**

Because in this example I pass `taskReceiptStruct` to `.withArgs` as a JS obj. Something like:

```
const taskReceiptStruct = { 
     id: 1, 
     userProxy: "0xad..", 
     task: { 
         foo: "0xdff...", 
         next: 2, 
         bar: ["0xfa."] 
     } 
}
```

It would be great to get some help on this issue.

Thank you!

**Comment by ricmoo** [comment]
I don’t know Chai and that error doesn’t look like it is coming from ethers. Can you provide an example that just uses ethers?

**Comment by gitpusha** [comment]
As discussed in Gitter @ricmoo, I am pretty sure the issue is here: `.withArgs(taskReceiptStruct);`

I pass `taskReceiptStruct` as a nested JS obj. However, ethers v4 structs in parsed event logs are represented as `Arrays`. So that's where the errror comes from, I am pretty certain.

**Comment by gitpusha** [comment]
Hi,

So I have an update on this:

I now use a script to convert my nested JS Obj that should represent a nested Solidity struct into an ethers v4 complian nested Array that is supposed to match the Array you get from parsing the event log in which the nested solidity struct was emitted.

I have made some progress in my waffle test but I am stuck with this:

The nested Struct JS Obj which I converted into an Array in order to test, whether it is emitted in an event:
```
[
  BigNumber { _hex: '0x01' },
  '0x6CBb2766B408f9A603792b8B546169E0b6Ad47ae',
  [
    [ [Array], [], [Array], [BigNumber], false ],
    BigNumber { _hex: '0x01' },
    []
  ]
]
```

The actual array representation thereof that I fetch from the parsed event log:
```
[
  BigNumber { _hex: '0x01' },
  '0x6CBb2766B408f9A603792b8B546169E0b6Ad47ae',
  [
    [ [Array], [], [Array], [BigNumber], false ],
    BigNumber { _hex: '0x01' },
    []
  ]
]
```

Hence, this looks pretty similar to me.

I also checked if the 2 arrays are similar using the recursive function (converting all elements to String)

```
function nestedArraysEqual(a, b) {
  if (a === b) return true;
  if (a == null || b == null) return false;
  if (a.length != b.length) return false;

  for (var i = 0; i < a.length; ++i) {
    // console.log(
    //   `${a[i]} !== ${b[i]}  ? : ${a[i].toString() !== b[i].toString()}`
    // );
    if (Array.isArray(a[i])) return nestedArraysEqual(a[i], b[i]);
    if (a[i].toString() !== b[i].toString()) return false;
  }
  return true;
}
```

And this function tells me the 2 arrays are equals.

So I wanna test if the struct is emitted in an event:

`.withArgs(taskReceiptAsArray);`

But waffle gives me this error:

![image](https://user-images.githubusercontent.com/36712489/81288861-b5896b00-9065-11ea-950f-f9ae9399f7ee.png)

```
      at assertArgsArraysEqual (node_modules/@ethereum-waffle/chai/dist/cjs/matchers/emit.js:37:59)
      at tryAssertArgsArraysEqual (node_modules/@ethereum-waffle/chai/dist/cjs/matchers/emit.js:47:20)
      at /Users/luis/Desktop/gelato-V1/node_modules/@ethereum-waffle/chai/dist/cjs/matchers/emit.js:59:13
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at Context.<anonymous> (test/gelato_core/core/task_cycles/cycle.test.js:215:5)
```

At this point I assume that the waffle chai emit matcher does not know how to compare nested ethers v4 style Array representations of nested Structs from parsed Event Logs.

@ricmoo Do you maybe have any idea why this comparison fails?

**Comment by sz-piotr** [comment]
@gitpusha Yeah, it is probably the case that the matcher could do a better job comparing the arrays.

**Comment by gitpusha** [comment]
Hi @sz-piotr . Thanks for stepping in. Yes, indeed. However, apparently there is a significant difference in the way `ethers-v4` and `ethers-v5` represent nested solidity structs in the parsed event logs. I intend to switch over to `ethers-v5` as soon as `Waffle` supports it too. 

Do you think you will release an update fixing this for v4 still any time soon, or is it not a prio?

**Comment by sz-piotr** [comment]
Hard to tell. Currently we have our eyes set straight on Waffle 3.0.0 with Ethers 5.0.0 support. If bugs for waffle v2 keep piling up we'll probably release another v2 version.

**Comment by marekkirejczyk** [comment]
Hi @gitpusha,

That looks like something we should do. 
Currently however we are snowed under projects and it is hard to find just couple hours to fix it. 
We are looking for new people to join, so they can help, will let you know as soon as we have more time.

Marek

**Comment by novaknole** [comment]
Hi all.. 

Same problem for me too even in 2021..


@gitpusha @marekkirejczyk  any interesting workaround you followed ? I'd appreciate if you could share it ..

**Comment by gitpusha** [comment]
Hey @novaknole - havent run into this in my code recently so sorry can't help with a quick workaround right now.

**Comment by drgorillamd** [comment]
Still having the issue, we used the following workaround @ juicebox (ie pushing every value in a new array, effectively getting rid of the Result object from ethers): https://github.com/jbx-protocol/juice-contracts-v2/blob/405d67c16ed150313912d9a64dbf92f19cb7bbb1/test/jb_splits_store/set.test.js#L68

Unfortunately, it's not always possible (for instance when having the same events n-times within the same tx) :/

**Comment by nkuba** [comment]
I also experienced this problem for an array nested in a struct:

```
      AssertionError: expected [] to equal []
      + expected - actual


      at assertArgsArraysEqual (node_modules/@ethereum-waffle/chai/dist/cjs/matchers/emit.js:48:57)
      at tryAssertArgsArraysEqual (node_modules/@ethereum-waffle/chai/dist/cjs/matchers/emit.js:65:20)
      at /Users/jakub/workspace/project/node_modules/@ethereum-waffle/chai/dist/cjs/matchers/emit.js:77:13
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at runNextTicks (internal/process/task_queues.js:64:3)
      at listOnTimeout (internal/timers.js:526:9)
      at processTimers (internal/timers.js:500:7)
```

**Comment by outdoteth** [comment]
Yep getting the same issue:

      Uncaught AssertionError: expected [] to equal []
      + expected - actual

**Comment by wei3erHase** [comment]
having the same issue here! is there a proper way of solving this?

**Comment by rzadp** [comment]
We have some more resources in our internal team and are able to look into it now.
I will keep you updated in this issue.

If anyone has a workaround for now, please do share.

**Comment by rzadp** [comment]
Structs in the arguments are now handled in Waffle 4.
Feel free to open new issues if you encounter any problems with it in Waffle 4.

**Comment by janbro** [comment]
I ran into this problem testing an event which returns a struct array, and taking a look at the changes to fix this issue, it seems like the case of struct arrays will not be fixed. The code would short circuit here since the expectedArgs[index] is an array https://github.com/TrueFiEng/Waffle/commit/b9af4f0d7fc99cd8ca3950aa9c9de31bd933c0ee#diff-8213c5fcf48a8703531394a5bde4bd4afa84d2b46bdf292cf94fa46fa0bf8fe8R30 and this ends up doing a normal equals comparison https://github.com/TrueFiEng/Waffle/commit/b9af4f0d7fc99cd8ca3950aa9c9de31bd933c0ee#diff-8213c5fcf48a8703531394a5bde4bd4afa84d2b46bdf292cf94fa46fa0bf8fe8R37-R39.
