### ISSUE TITLE
Add issue template for bug reports / feature requests

### ISSUE THREAD

**Issue by wachulski** [TrueFiEng/Waffle#491]
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

Two reasons:

- several feature requests have been created recently
- I see bug reports often do not detail the following
  -  which version of waffle they use
  - what integrations they use (+ versions), e.g. hardhat/typechain, ethers lib, etc.
  - waffle settings they used
  - etc.

so all contextual information necessary to quickly repro steps.

**Comment by rzadp** [comment]
Done.
