### ISSUE TITLE
compileDockerSolc command incorrect

### ISSUE THREAD

**Issue by hmmdeif** [TrueFiEng/Waffle#495]
System: Windows 10

waffle.json
```
{
    "compilerType": "dockerized-solc",
    "compilerVersion": "0.8.4"
}
```

When building using `waffle` this adds `solc` to the docker run command which ends up being rejected with the error `File not found: solc` reported in the docker container. If I remove the word `solc` from the command it compiles fine so it becomes:

```
    return `docker run ${getVolumes(config)} -i -a stdin -a stdout ` +
        `ethereum/solc:${tag} --standard-json --allow-paths ${allowedPaths}`;
```

Is this a Windows docker thing and does this work for anyone else without changing the code? Does anyone know of a reason why this command would not work by default?

**Comment by rzadp** [comment]
This is not a Windows-specific problem. I have reproduced it on macOS.

Looks like something has changed in the solc docker image in some version.
I will continue to look into it.
