### ISSUE TITLE
Add chai matchers for Solidity 0.8.4 custom errors

### ISSUE THREAD

**Issue by iconofsin** [TrueFiEng/Waffle#511]

**Comment by paulrberg** [comment]
Yes, please!

**Comment by lepidotteri** [comment]
+1

**Comment by paulrberg** [comment]
Hardhat added support for custom errors in the [v2.4.0](https://github.com/nomiclabs/hardhat/releases/tag/hardhat-core-v2.4.0) release. Thus an interrim solution for Waffle users is the following:

```ts
await expect(myContract.myFunction()).to.be.revertedWith("MyCustomError");
```

I would expect a more idiosyncratic chai matcher if Waffle is to implement this, but the above should be good enough for now.

**Comment by lepidotteri** [comment]
> Hardhat added support for custom errors in the [v2.4.0](https://github.com/nomiclabs/hardhat/releases/tag/hardhat-core-v2.4.0) release. Thus an interrim solution for Waffle users is the following:
> 
> ```ts
> await expect(myContract.myFunction()).to.be.revertedWith("MyCustomError");
> ```
> 
> I would expect a more idiosyncratic chai matcher if Waffle is to implement this, but the above should be good enough for now. This is the full string that Hardhat emits:
> 
> > Error: VM Exception while processing transaction: reverted with custom error 'MyCustomError()'

@marekkirejczyk Is this already in the roadmap for 4.0?

**Comment by StErMi** [comment]
that would be amazing!

**Comment by michaeljohnbennett** [comment]
> Hardhat added support for custom errors in the [v2.4.0](https://github.com/nomiclabs/hardhat/releases/tag/hardhat-core-v2.4.0) release. Thus an interrim solution for Waffle users is the following:
> 
> ```ts
> await expect(myContract.myFunction()).to.be.revertedWith("MyCustomError");
> ```
> 
> I would expect a more idiosyncratic chai matcher if Waffle is to implement this, but the above should be good enough for now. This is the full string that Hardhat emits:
> 
> > Error: VM Exception while processing transaction: reverted with custom error 'MyCustomError()'

Is there a way to check the value for the error if you are returning?

```
AssertionError: Expected transaction to be reverted with Unauthorized("!ADMIN"), 
but other exception was thrown: Error: 
VM Exception while processing transaction: reverted with custom error 'Unauthorized("!ADMIN")'

// where the assert is: 
....method..to.be.revertedWith('Unauthorized("!ADMIN")');

```

Just doing the error name on its own is fine, but you might want some more fine grained checks in place. Errors seem great but its not great if you wanted to make the errors a little more descriptive, rather than throwing in loads of specific error types for each scenario.

**Comment by paulrberg** [comment]
Hey @michaeljohnbennett, does it work if you escape the double quotes?

```ts
....method..to.be.revertedWith("Unauthorized(\"!ADMIN\")");
```

**Comment by michaeljohnbennett** [comment]
ok I see. so you would have a multitude of error types for all those cases and 0 strings? 

I can understand gas efficiency but then your going to have to have some kind of mapping in external code to understand or give you users some meaningful message, don't you think thats an added complexity? 

I thought the whole purpose of an error object was to tell someone an error had occurred and some meaningful text/message to tell them more or less what happened.

Strangely after further testing this afternoon on a hardhat-deploy templated project it does work for the message value being emitted and not picking up the error wrapper. But this behaviour seems to change sometimes, randomly.

I will clean my node_modules down and try fresh and see how I go.

Thanks again for the reply @paulrberg , appreciated as always. 👍🏻

**Comment by paulrberg** [comment]
> ok I see. so you would have a multitude of error types for all those cases and 0 strings?

Yes, that is what I do. Here's  a list of projects I built or contributed to that use 100% only custom errors:

- https://github.com/hifi-finance/prb-math
- https://github.com/paulrberg/contracts (see [Ownable](https://github.com/paulrberg/contracts/blob/068d2309c3a3bcc899f12d21cd664d6dee4e04c5/contracts/access/Ownable.sol) and [Erc20](https://github.com/paulrberg/contracts/blob/068d2309c3a3bcc899f12d21cd664d6dee4e04c5/contracts/token/erc20/Erc20.sol))
- https://github.com/hifi-finance/hifi (in particular see the [protocol](https://github.com/hifi-finance/hifi/tree/main/packages/protocol) package)

> I can understand gas efficiency but then your going to have to have some kind of mapping in external code to understand or give you users some meaningful message, don't you think thats an added complexity?

It's not. The Ethereum ecosystem will sooner or later support custom errors across the board. For instance, I know that Etherscan is working on decoding custom errors and displaying the actual error name when a transaction fails.

> I thought the whole purpose of an error object was to tell someone an error had occurred and some meaningful text/message to tell them more or less what happened.

Now the custom error themselves is the "text/message" that tells the user what happened. Did you read the [announcement post](https://blog.soliditylang.org/2021/04/21/custom-errors/)?

Though custom errors need not have zero arguments. Sometimes you may want to log the function inputs, but usually those are `uint256`. See the projects referenced above.

**Comment by CJ42** [comment]
I agree with @paulrberg. Custom errors will soon be widely used across the Ethereum smart contracts and Dapp ecosystem.

I have found a current work around to make sure the parameters inside the custom error match, until Waffle implement this.

```solidity
MyCustomError(address _address, string _string);
```

```javascript
const customRevertErrorMessage =
      "VM Exception while processing transaction: reverted with custom error";

it("should revert with MyCustomError and correct parameters", async () => {
    const expectedErrorParam1 = "0xcafecafecafecafecafecafecafecafecafecafe";
    const expectedErrorParam2 = "Some String";
    
    try {
        await myContract.myFunction()
    } catch (error) {
        expect(error.message).toMatch(
            `${customRevertErrorMessage} 'MyCustomError("${expectedErrorParam1}", "${expectedErrorParam2}")'`
        )
    }
})
```

**NB: don't forget the single quotes** between `MyCustomError` in the message inside `.toMatch()`.

So ✅ 
```
VM Exception while processing transaction: reverted with custom error 'MyCustomErrror(...)'
```

Not ❌ 
```
VM Exception while processing transaction: reverted with custom error MyCustom(...)
```

**Comment by michaeljohnbennett** [comment]
You could also make a fixture like so to use in your code:

Using the promises chaining API you can add something like this that would pass/fail and catch both possibilities in call.

```typescript
async function assertErrorMessage(
      p: Promise<ContractTransaction>,
      message: string
    ): Promise<void> {
      return p.then(
        (value) => {
          expect.fail(`Found value instead of error: ${value}`);
        },
        (reason) => {
          expect(reason.message).to.contain(message);
        }
      );
    }

// and call it like so:
await assertErrorMessage(
  myTypechainContractInstance.someMethod(3, 2, 1, 4),
  'SomeMethod_ErrorWithParams(0, 3)'
);
```

I'm using hardhat and typechain here for this example in typescript but its easy enough to remove the types and using plain JS too. And you can use your interpolated strings too if you like in the function call or add some lambda func to build that up for you as a helper.

This way you can put it in a helper import or similar for your tests and not have them littered with try/catch blocks.

**Comment by itinance** [comment]
Almost a year later, there is no progress on this particular topic. However, is this something to expect in future or was it skipped at all?

**Comment by yivlad** [comment]
Added support for the feature when using with `hardhat` in the latest [alpha release](https://github.com/TrueFiEng/Waffle/releases/tag/ethereum-waffle%404.0.0-alpha.24). Available on `npm` under the `alpha` tag. 
Not supported for now by `@ethereum-waffle/provider` as it internally uses `ganache`. Although the feature can be added to `@ethereum-waffle/provider` as well - but would require a few manual steps from user such as manually registering contract's ABI. Would love to hear your feedback on that.

**Comment by iconofsin** [comment]
It seems to be working, i.e. I can no longer match an `error Unauthorized(address)` with just `revertedWith("Unauthorized")`, and it does include the error argument in the diag output. What's the proper way to match these, though? I was thinking something along the lines of how `emit` operates, `emit(contract, 'EventName').withArgs(...)`, but doesn't look like anything of the sort is there?

Should it be a regex match instead?

**Comment by paulrberg** [comment]
The custom errors arguments should definitely be testable via `withArgs`, just like event arguments are.

**Comment by rzadp** [comment]
Custom errors are now available in Waffle 4 - you can match against a custom error, including the custom error arguments.

Example usage:

```ts
await expect(matchers.doRevertWithOne()).to.be.revertedWith('One');
```

```ts
await expect(matchers.doRevertWithOne())
  .to.be.revertedWith('One')
  .withArgs(
    0,
    'message',
    '0x00cfbbaf7ddb3a1476767101c12a0162e241fbad2a0162e2410cfbbaf7162123'
);
```

Note that this only works in a setup with hardhat, with contracts compiled with hardhat.
