### ISSUE TITLE
Update ethers dependencies to fix "invalid fragment object" error

### ISSUE THREAD

**Issue by paulrberg** [TrueFiEng/Waffle#531]
See https://github.com/ethers-io/ethers.js/issues/1493.

**Comment by PierrickGT** [comment]
> See [ethers-io/ethers.js#1493](https://github.com/ethers-io/ethers.js/issues/1493).

@paulrberg has this issue been resolved? I'm having the same kind of error on version 3.4.0.

**Comment by paulrberg** [comment]
I'm not sure, I haven't used this lately.

**Comment by PierrickGT** [comment]
> I'm not sure, I haven't used this lately.

Thanks for your feedback. Looks like this is just a warning, my tests and compilation run perfectly despite this error message.
