### ISSUE TITLE
Can't install ethereum-waffle

### ISSUE THREAD

**Issue by torupapat** [TrueFiEng/Waffle#533]
I tried to install ethereum-waffle and this error happened
```
 npm ERR! code ENOENT
 npm ERR! syscall spawn git
 npm ERR! path git
 npm ERR! errno -4058
 npm ERR! enoent Error while executing:
 npm ERR! enoent undefined ls-remote -h -t https://github.com/ethereumjs/ethereumjs-abi.git
 npm ERR! enoent
 npm ERR! enoent
 npm ERR! enoent spawn git ENOENT
 npm ERR! enoent This is related to npm not being able to find a file.
 npm ERR! enoent 
```
I don't know this gonna help, but this is my package.json file look like
```
   "name": "solidity-pj",
   "version": "1.0.0",
   "description": "",
   "scripts": {
     "test": "echo \"Error: no test specified\" && exit 1"
   },
   "keywords": [],
   "author": "",
   "license": "ISC",
   "devDependencies": {
     "@nomiclabs/hardhat-ethers": "^2.0.2",
     "@nomiclabs/hardhat-waffle": "^2.0.1",
     "@openzeppelin/contracts": "^4.1.0",
     "chai": "^4.3.4",
     "ethers": "^5.3.1",
     "git": "^0.1.5",
     "hardhat": "^2.4.1",
     "solidity-coverage": "^0.7.16"
```
Please tell me what I did wrong. Thank a lot!
OS : Windows 10
Program : VScode

**Comment by Michu44** [comment]
I have the same issue!

**Comment by wang-hang** [comment]
I have the same issue!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!   anyone can  help???

**Comment by vitor-ramalho** [comment]
@wang-hang u tried to update nodejs to v16+ and install ethereum-waffle again ?

**Comment by wang-hang** [comment]
> 

@vitor-ramalho  i updated to v16+  and it works well~~

**Comment by AAAZZZR** [comment]
Node v16-16, npm v8.11 still get false.

**Comment by rzadp** [comment]
@AAAZZZR What is the output in your terminal? What's the actual error?

**Comment by zhangjiazjj** [comment]
**Y just need to replace** {ethereumjs-abi@^0.6.8:
  version "0.6.8"
  resolved "https://registry.npmmirror.com/ethereumjs-abi/-/ethereumjs-abi-0.6.8.tgz#71bc152db099f70e62f108b7cdfca1b362c6fcae"
  integrity sha512-Tx0r/iXI6r+lRsdvkFDlut0N08jWMnKRZ6Gkq+Nmw75lZe4e6o3EkSnkaBP5NF6+m5PTGAr9JP43N3LyeoglsA==
  dependencies:
    bn.js "^4.11.8"
    ethereumjs-util "^6.0.0"} **in yarn.lock with** 
{"ethereumjs-abi@git+https://github.com/ethereumjs/ethereumjs-abi.git":
  version "0.6.8"
  resolved "https://registry.yarnpkg.com/ethereumjs-abi/-/ethereumjs-abi-0.6.8.tgz#71bc152db099f70e62f108b7cdfca1b362c6fcae"
  integrity sha512-Tx0r/iXI6r+lRsdvkFDlut0N08jWMnKRZ6Gkq+Nmw75lZe4e6o3EkSnkaBP5NF6+m5PTGAr9JP43N3LyeoglsA==
  dependencies:
    bn.js "^4.11.8"
    ethereumjs-util "^6.0.0"}

**and then it works well**
