### ISSUE TITLE
Event emitter is not capturing event with args on nested functions

### ISSUE THREAD

**Issue by 0xjjpa** [TrueFiEng/Waffle#537]
# Introduction

We are currently expanding our tests in hoprnet/hoprnet#2077 to include arguments to verify the proper emitting of the events in our contracts. In the past, we only verified that the events were called, but did not make sure that the arguments were indeed being passed properly.

When implementing `.withArgs` in hoprnet/hoprnet@58d2c88, the following error was thrown by `waffle-chai@3.2` when running `hardhat test`

![image](https://user-images.githubusercontent.com/1128312/124905517-67b02000-dfe6-11eb-8a6b-503c575946fa.png).

This was unlikely as a quick `console.log` on both contracts and tests showed parameters were indeed being passed properly. My guess was that `waffle-chai` wasn't picking up events on nested calls, as I couldn't find any test that could verify this. Thus, I created #536, trying to replicate the error without success. Unfortunately, our contracts are on `solidity ^0.8` so that might not be an effective way to replicate the issue.

# Expected behavior

Given the following tests where the contracts had been mocked via `ethers` `deployments.createFixtures`, as seen [here](https://github.com/hoprnet/hoprnet/blob/58d2c885d375e6b36a69588f4eb9f00a8a140202/packages/ethereum/test/HoprChannels.spec.ts#L168-L193), verifying the emitting of a specific event using `.withArgs` should pick up the event with the proper arguments, as previously done successfully [here](https://github.com/hoprnet/hoprnet/blob/58d2c885d375e6b36a69588f4eb9f00a8a140202/packages/ethereum/test/HoprChannels.spec.ts#L607-L618).

```typescript
await expect(channels.connect(accountA).fundChannelMulti(ACCOUNT_A.address, ACCOUNT_B.address, '70', '30'))
      .to.emit(channels.connect(accountA), 'ChannelUpdate')
      .withArgs(
        ACCOUNT_A.address,
        ACCOUNT_B.address,
        createMockChannelFromMerge(
          await channels.channels(ACCOUNT_AB_CHANNEL_ID),
          createMockChannelFromProps({
            balance: BigNumber.from(70)
          })
        )
      )
```

The smart contract function looks as follows:

```solidity
 /**
     * @dev Funds channels, in both directions, between 2 parties.
     * then emits {ChannelUpdate} event, for each channel.
     * @param account1 the address of account1
     * @param account2 the address of account2
     * @param amount1 amount to fund account1
     * @param amount2 amount to fund account2
     */
    function fundChannelMulti(
        address account1,
        address account2,
        uint256 amount1,
        uint256 amount2
    ) external {
        require(amount1.add(amount2) > 0, "amount must be greater than 0");
        token.safeTransferFrom(msg.sender, address(this), amount1.add(amount2));
        if (amount1 > 0){
          _fundChannel(account1, account2, amount1);
        }
        if (amount2 > 0){
          _fundChannel(account2, account1, amount2);
        }
    }
```

which in turn calls the actual event emitter function `_fundChannel`:

```solidity
/**
     * @dev Funds a channel, then emits
     * {ChannelUpdate} event.
     * @param source the address of the channel source
     * @param dest the address of the channel destination
     * @param amount amount to fund account1
     */
    function _fundChannel(
        address source,
        address dest,
        uint256 amount
    ) internal {
        _validateSourceAndDest(source, dest);
        require(amount > 0, "amount must be greater than 0");

        (, Channel storage channel) = _getChannel(source, dest);
        require(channel.status != ChannelStatus.PENDING_TO_CLOSE, "Cannot fund a closing channel"); 
        if (channel.status == ChannelStatus.CLOSED) {
          // We are reopening the channel
          channel.channelEpoch = channel.channelEpoch.add(1);
          channel.ticketEpoch = 0; // As we've incremented the channel epoch, we can restart the ticket counter
          channel.ticketIndex = 0;

          if (channel.commitment != bytes32(0)) {
            channel.status = ChannelStatus.OPEN;
          } else {
            channel.status = ChannelStatus.WAITING_FOR_COMMITMENT;
          }
        }

        channel.balance = channel.balance.add(amount);
        emit ChannelUpdate(source, dest, channel);
    }
```

# Current behavior

The test currently fails, showing an `AssertionError: Specified args not emitted in any of 2 emitted "ChannelUpdate" events`. The event is clearly fired, but the arguments are not being picked up.

# Possible solution

No current solution as #536 is passing.

# Steps to reproduce

Within hoprnet/hoprnet@58d2c88, run `yarn test:contracts test/HoprChannels.spec.ts`. Within the current repository, I've been unable to replicate the error, although might be a disparity in solidity versions.

# Additional information

Removing the `.withArgs` would return the test to green. This is relevant for in hoprnet/hoprnet#2078

**Comment by NoahMarconi** [comment]
Not a proper fix but some non waffle code that can match:

```
export const containsEvent = (receipt: any, instance: Contract, eventName: string, eventArgs: any[]) => {

    let res = false;

    let events = receipt.events
        // Only relevant address.
        .filter((x: Event) => x.address.toLowerCase() === instance.address.toLowerCase())
        // Parse Events.
        .map((e: Event) => { return instance.interface.parseLog(e); })
        // Only relevant event name.
        .filter((x: LogDescription) => { return x.name == eventName; });

    events.forEach((event: LogDescription) => {
        const inputParamTypes = event.eventFragment.inputs;
        const isMatch = event.args?.reduce((acc: boolean, currentValue: any, currentIndex: number) => {
            let localRes;
            if (inputParamTypes[currentIndex].type === 'address') {
                localRes = ethers.utils.getAddress(currentValue) === ethers.utils.getAddress(eventArgs[currentIndex]);
            } else if (inputParamTypes[currentIndex].type === 'uint256') {
                localRes = currentValue.eq(eventArgs[currentIndex]);
            } else {
                localRes = currentValue === eventArgs[currentIndex];
                console.log(`${eventName} arg ${currentIndex} ${currentValue} === ${eventArgs[currentIndex]}  ${localRes}`);
            }
            return acc && localRes;
         },  true);

         if(isMatch) {
             res = isMatch;
         }
    });

    return res;
}
```

Why this works and waffle's doesn't is that the event names are not coming from ethers, you have to parse with the Contract's interface first, and then the names are present and filterable:

```
.map((e: Event) => { return instance.interface.parseLog(e); })
```

I'm short for time but in maybe a month if this is not fixed I might be able to submit a pull request with a more internal waffle correction, are you guys accepting external pull requests?

**Comment by rzadp** [comment]
@0xjjpa @NoahMarconi Is this still an issue for you?

Not sure what to do, given that:
- https://github.com/TrueFiEng/Waffle/pull/536 is passing
- _our contracts are on solidity `^0.8`_
Waffle is on `^0.8` as well and the test is still passing

**Comment by NoahMarconi** [comment]
My workaround solved my use case. I haven't had to test a scenario like this since and don't know if it's been handled by the lib or not.

The problem I note above is when the event is from another contract and does not appear in the calling contracts interface.

**Comment by rzadp** [comment]
> The problem I note above is when the event is from another contract and does not appear in the calling contracts interface.

I see. In this case, you do it like this: (where `library` is the contract containing the events definitions and emitting them)


![Screenshot 2022-08-01 at 15 29 58](https://user-images.githubusercontent.com/12039224/182159060-55508c67-28d6-4206-ad1b-1292a72a4fbe.png)
