### ISSUE TITLE
@ethereum-waffle/jest type annotation support

### ISSUE THREAD

**Issue by wiasliaw** [TrueFiEng/Waffle#538]
I'm using @ethereum-waffle/jest with ts-jest and  ethers.js. 

However, the error happened due to that `expect.extend()` doesn't extend matchers' type.

**ABI**
```
"humanReadableAbi": [
  "function get() view returns(int256)",
  "function set(int256 val)"
]
```

**Test**
```typescript
import { waffleJest } from '@ethereum-waffle/jest';
expect.extend(waffleJest);

// the `expect` doesn't get the type of matchers
// error log: `Property 'toEqBN' does not exist on type 'JestMatchers<any>'`
expect(await contract.connect(signer).get()).toEqBN(expectedValue);
```

**Comment by 0xTeaTwo** [comment]
This is not waffle's problem, but jest's practice.
How to add type to custom matcher is [here](https://jestjs.io/ja/docs/expect#expectextendmatchers).

But there is other problem that type definition unmatched.

I seem that a type definition `https://github.com/EthWorks/Waffle/blob/master/waffle-jest/src/types.d.ts` is correct.
But the setting in npm publish points another type definition `https://github.com/EthWorks/Waffle/blob/master/waffle-jest/package.json#L28`. Therefore, even if I set it according to the JEST document, an error occurs.

**Comment by rzadp** [comment]
Going forward in Waffle 4, we have decided to deprecate support of Jest and focus on chai exclusively.
We offer a migration guide for the matchers: https://ethereum-waffle.readthedocs.io/en/latest/migration-guides.html#ethereum-waffle-jest-deprecated
