### ISSUE TITLE
chai: Combine `changeTokenBalance` with `emit` matcher

### ISSUE THREAD

**Issue by sebastianst** [TrueFiEng/Waffle#556]
I used to have a test like
```ts
    await expect(await erc20HolderSession.deposit(token.address, amount))
      .to.changeTokenBalance(token, erc20Holder, amount) // broken
      .and.emit(token, "Transfer");
```
which combines a token change and event emittance assertion. It doesn't work any more and fails with `TypeError: transactionCall is not a function`. As per the [docs](https://ethereum-waffle.readthedocs.io/en/latest/matchers.html#change-token-balance) I have to use a callback now:
```ts
    await expect(() => erc20HolderSession.deposit(token.address, amount))
      .to.changeTokenBalance(token, erc20Holder, amount) // works now
      .and.emit(token, "Transfer"); // broken
```
Now the `changeTokenBalance` assertion works again, but the next `and.emit` is broken, it fails with `Error: () => erc20HolderSession.deposit(token.address, amount) is not a valid transaction`.

So the dilemma seems that I have to pass a callback for `changeTokenBalance` but a promise for `emit`.

Note that the same code _still works_ for `changeEtherBalance`:
```ts
await expect(await ethHolderAlice.deposit({value: amount}))
      .to.changeEtherBalance(ethHolder, amount)
      .and.emit(someOtherContract, "Deposited");
```

So my question is: how to properly combine token balance change and event emittance assertions?

**Comment by sebastianst** [comment]
I found an ugly-looking workaround:
```ts
    let tx: Promise<ContractTransaction>;
    await expect(() => { tx = erc20HolderSession.deposit(token.address, amount); return tx })
      .to.changeTokenBalance(token, erc20Holder, amount);
    await expect(tx!).to.emit(token, "Transfer");
```
which captures the first assertion's transaction promise and then reuses it for the `emit` assertion. But that's not very nice to use... there should be some way to chain these calls.

**Comment by sebastianst** [comment]
Slightly funnier work-around:
```ts
 await expect(() =>
      expect(erc20HolderSession.deposit(token.address, amount))
      .to.emit(token, "Transfer")
    )
      .to.changeTokenBalance(token, erc20Holder, amount);
```

**Comment by johanneskares** [comment]
> Slightly funnier work-around:
> 
> ```ts
>  await expect(() =>
>       expect(erc20HolderSession.deposit(token.address, amount))
>       .to.emit(token, "Transfer"))
>       .to.changeTokenBalance(token, erc20Holder, amount);
> ```
> 
> which works because we execute the emit assertion [here](https://github.com/EthWorks/Waffle/blob/3f46a6c8093cb9edb1a68c3ba15c4b4499ad595d/waffle-chai/src/matchers/changeTokenBalance.ts#L40).

Doesn't work for me, unfortunately. It seems to pass, but when I change the name of the emitted event to something random, it still passes.

**Comment by yivlad** [comment]
Support added in the latest [alpha release](https://github.com/TrueFiEng/Waffle/releases/tag/ethereum-waffle%404.0.0-alpha.24). Available on `npm` under the `alpha` tag.
