### ISSUE TITLE
Transferring ethers to a mocked contract

### ISSUE THREAD

**Issue by RomualdH** [TrueFiEng/Waffle#557]
Hello all,

I'm trying to understand if there is an issue with Waffle or it's my lack of knowledge...

When transferring ethers from a contract to a mocked contract, I get the error `contract call run out of gas and made the transaction revert` even though the caller contract balance has enough. 
This is the simple Test contract:
```solidity
pragma solidity ^0.8.0;
import "hardhat/console.sol";

contract Test {
    address payable public receiver;

    constructor(address payable _receiver) {
        receiver = _receiver;
    }

    function transferTest(uint256 amount) external {
        console.log("Contract balance", address(this).balance);
        console.log("Amount to be transfered", amount);
        receiver.transfer(amount);
    }

    receive() external payable {}
}
```

The reproduction steps are:

1. Deploy the `receiver` mocked contract
2. Deploy the `Test` contract with `receiver`'s contract address as argument
3. Send ethers to the `Test` contract
4. Call the `deployedTest.transferTest` function

Thank you in advance.

**Comment by sebastiantf** [comment]
Is there no way to transfer some ether into or increase the ether balance of a mocked contract?
