### ISSUE TITLE
False-negative: revertedWith succeeds despite only partial match

### ISSUE THREAD

**Issue by skywinder** [TrueFiEng/Waffle#558]
- Affected versions 3.4.0
- **Error should's fixed in #442 and still persist in latest version**
- Related Issue: #400

### False-negative scenario:

The method should be reverted with `"onlyWorker: bad role"`

`.to.be.revertedWith("onlyWorker: bad role");`

### True-negative case (original string):

<img width="415" alt="CleanShot 2021-08-19 at 18 13 41@2x" src="https://user-images.githubusercontent.com/3356474/130059369-2df80c9e-0e0b-4b79-a6e4-cf0fc35d1494.png">

### False-negative scenario (it pass, but should fail)

if I remove the beginning or ending part of the `reveredWith` parameter - it still passes the tests:

`.to.be.revertedWith("onlyWorker: bad");`
`.to.be.revertedWith("bad role");`

<img width="471" alt="CleanShot 2021-08-19 at 18 13 19@2x" src="https://user-images.githubusercontent.com/3356474/130059396-49dee223-47d1-4ece-ac0a-e883ef376b55.png">

**Comment by Theo6890** [comment]
Up, I've just encountered this partial match issue! Maybe we can have `revertedWith` and add `revertedWithExact`

**Comment by skywinder** [comment]
@Theo6890 the thing, that it's not expected behavior for `revertedWith`, so there is not a reason to add another method.

They have even test for this case:

[message](https://github.com/EthWorks/Waffle/blob/dc7afe41859182b79e813956ea9f46a7cefb7f6d/waffle-chai/test/matchers/reverted.test.ts#L85-L89)

**Comment by skywinder** [comment]
related issue: https://github.com/EthWorks/Waffle/issues/511

**Comment by or2008** [comment]
I have the same issue, test pass even if the error returned is completely different..

**Comment by rzadp** [comment]
In Waffle 4, we have reworked the way revert messages are extracted, and the partial-match problem should now be resolved.
Please feel free to reopen if you still encounter this in Waffle 4.
