### ISSUE TITLE
chai: `withIndexedArgs` events matcher (or partial args)

### ISSUE THREAD

**Issue by sebastianst** [TrueFiEng/Waffle#568]
I propose to add a new chai matcher to the `emit` chain that only matches indexed arguments: `withIndexedArgs`.

I'm writing tests for a contract that emit an event like the following:
```solidity
    struct TokenValue {
        address token;
        bytes value;
    }

    event Withdrawn(uint64 indexed epoch, address indexed account, TokenValue[] tokens);
```
I couldn't get `withArgs` to work, no matter what I specified as the third argument. For practical purposes, it would also be sufficient to match the first two arguments. So `withIndexedArgs` would easily let me match on the first two `uint64` and `address` indexed arguments. Also, indexed arguments are internally treated differently, as topics, so this would actually be a simplified version of the `withArgs` matcher.

Alternatively, we could also add some means to the `withArgs` matcher to allow any value at some position. E.g., we could let a value of `null` at an argument's position indicate that we want to allow any value for this position.

I would also be happy to write a PR for this.

**Comment by StErMi** [comment]
I totally agree, we need something that allows us to also specify with args we want to check. Sometimes events have `date` as args (indexed or not) and it's not an easy task to validate those date values.

**Comment by julianmrodri** [comment]
+1 This would be SO helfpful...

**Comment by MidnightLightning** [comment]
Related request #437

**Comment by rzadp** [comment]
#437 is now completed and available in Waffle 4.
And this can be used to select any arguments that you want, omitting others, and it can be used to select only indexed arguments as well so I think it resolves this issue as well.
