### ISSUE TITLE
Chaining multiple `changeBalance` matchers without re-sending the transaction

### ISSUE THREAD

**Issue by marcelomorgado** [TrueFiEng/Waffle#569]
Hi,

When I have some expectation like this:
```javascript
const tx = () => contract.call()
await expect(tx).changeTokenBalances(token1, [...], [...])
  .and.to.changeTokenBalances(token2, [...], [...])
  .and.to.changeEtherBalances([...], [...])
```
The transaction is sent multiple times (one for each matcher), is there a way to work around this?

Thanks

**Comment by yivlad** [comment]
Support added in the latest [alpha release](https://github.com/TrueFiEng/Waffle/releases/tag/ethereum-waffle%404.0.0-alpha.24). Available on `npm` under the `alpha` tag.
