### ISSUE TITLE
AssertionError: Waffle's calledOnContract is not supported by Hardhat

### ISSUE THREAD

**Issue by JimLynchCodes** [TrueFiEng/Waffle#585]
See the project here: https://github.com/TDD-Solidity/Solidity-Mocking

"calledOnContract" fails with the error:

```
AssertionError: Waffle's calledOnContract is not supported by Hardhat
```

**Comment by carlomigueldy** [comment]
Same error as me

**Comment by rzadp** [comment]
We have it working now :)
You can see it in action here: https://github.com/TrueFiEng/Waffle/tree/master/waffle-hardhat
It's available in Waffle version 4.
