### ISSUE TITLE
chaining `.emit().withArgs()` not working as expected

### ISSUE THREAD

**Issue by paco0x** [TrueFiEng/Waffle#595]
If I write code like:

```solidity
await (tx).to.emit(ContractA, "EventA").withArgs(a)
    .to.emit(ContractA, "EventB").withArgs(b)
```

only the last `emit().withArgs()` works. Other checks are ignored. Is this expected behavior?

**Comment by julianmrodri** [comment]
Facing the same issue in some complex checks where multiple contracts emit the same event and share the same interface. At some point only the last one is checked and you can put any arbitrary data on all previous `to.emit` and they always pass. 

Is there a known issue or restriction when chaining this?

**Comment by julianmrodri** [comment]
Here I was able to reproduce this issue with a very SIMPLE example. Please let me know if you need additional information.

https://github.com/julianmrodri/multi-emit-example

**Comment by julianmrodri** [comment]
It can even be simplified to a single contract

```
contract EventEmitter is IEmitter {
    constructor(){}

    function emitTwice(uint256 val1, uint256 val2) external {
        emit EventHappened(val1, val2);
        emit EventHappened(val1+1, val2+1);
    }
}
and
  it("Should fail but passes -- wrong values", async () => {
    await expect(emitter1.emitTwice(val1, val2))
      .to.emit(emitter1, "EventHappened")
      .withArgs(23, 0)
      .and.to.emit(emitter1, "EventHappened")
      .withArgs(val1.add(1), val2.add(1));
  });
  ```

**Comment by MidnightLightning** [comment]
Not sure if it's intended to be chain-able, but that sort of multi-event test can be done by:

```
await (tx).to.emit(ContractA, "EventA").withArgs(a);
await (tx).to.emit(ContractA, "EventB").withArgs(b);
```

In other words, you can re-use the transaction (`tx`) object multiple times and it will verify each of them.

**Comment by paco0x** [comment]
> Not sure if it's intended to be chain-able, but that sort of multi-event test can be done by:
> 
> ```
> await (tx).to.emit(ContractA, "EventA").withArgs(a);
> await (tx).to.emit(ContractA, "EventB").withArgs(b);
> ```
> 
> In other words, you can re-use the transaction (`tx`) object multiple times and it will verify each of them.

Yea, this can work as expected but I wish the chaining method can also work too.

**Comment by yivlad** [comment]
Support added in the latest [alpha release](https://github.com/TrueFiEng/Waffle/releases/tag/ethereum-waffle%404.0.0-alpha.24). Available on `npm` under the `alpha` tag.
