### ISSUE TITLE
`revertedWith` does not escape single quote

### ISSUE THREAD

**Issue by LorranSutter** [TrueFiEng/Waffle#599]
### Scenario

There is a contract with a `require` message with a single quote within:

```
require(feed != address(0), "Quoter: asset doesn't have feed");
```
Write a test to cover this revert and it passes:

```ts
await expect(quoter.quotePrice(quoterImplementation.address, 0, asset.address))
        .to.be.revertedWith('Quoter: asset doesn\'t have feed');
```

Modify the string before the single quote and it fails:

```ts
await expect(quoter.quotePrice(quoterImplementation.address, 0, asset.address))
        .to.be.revertedWith('Quoter: \'t have feed');
```

Modify the string **after** the single quote and it passes:

```ts
await expect(quoter.quotePrice(quoterImplementation.address, 0, asset.address))
        .to.be.revertedWith('Quoter: asset doesn\'t');
```

It also happens with double quotes:

```ts
await expect(quoter.quotePrice(quoterImplementation.address, 0, asset.address))
        .to.be.revertedWith("Quoter: asset doesn't");
```

### Expected Scenario

It should fail if the string does not match.

**Comment by rzadp** [comment]
@LorranSutter I have [tested](https://github.com/TrueFiEng/Waffle/pull/767) it in Waffle 4 and it seems to be working fine - please feel free to reopen if you still have this problem.
