### ISSUE TITLE
TypeError: Factory is not a constructor

### ISSUE THREAD

**Issue by aliskhanoff** [TrueFiEng/Waffle#601]
I am trying to deploy contract using ABI format (downloaded from [etherscan](https://docs.etherscan.io/api-endpoints/contracts) api). When i call
`await deployContract(devWallet, output, [devWallet.address, 1000]);`

throws error:

> TypeError: Factory is not a constructor

>  at deployContract (D:\BlockchainTest\node_modules\ethereum-waffle\dist\cjs\deployContract.js:12:33)
>     at Context.<anonymous> (src\test\compile.test.js:24:23)
>    at processTicksAndRejections (node:internal/process/task_queues:96:5)

I am using Javascript

**Comment by rzadp** [comment]
This should already be fixed after https://github.com/TrueFiEng/Waffle/pull/648
Feel free to reopen if you still have this problem on Waffle version 4.
