### ISSUE TITLE
`npx waffle` gives: command not found: waffle

### ISSUE THREAD

**Issue by pguardiario** [TrueFiEng/Waffle#611]
I get this output from `npx waffle`
npx: installed 12 in 1.734s
command not found: waffle

This is on windows 10 with node 14.18.3

I'm not sure what I'm doing wrong, this might be a npx issue but I'm able to do other npx commands fine.
I'm following the instructions in the readme and I really want to try this lib.

**Comment by rzadp** [comment]
@pguardiario Looks like you missed an installation step https://ethereum-waffle.readthedocs.io/en/latest/getting-started.html#installation
Then npx executes `waffle` executable from `node_modules`.

If you want to try it out without installing, the command would be
```
npx ethereum-waffle
```
