### ISSUE TITLE
revertedWith automatically appends a Dot on the expected revert-message when it won't match

### ISSUE THREAD

**Issue by itinance** [TrueFiEng/Waffle#628]
I came across a weird issue: when a revert-message did not match 100% (like uppercase/lowercase or misspelled carachters), revertedWith will magically add a Dot at the end of the message (which could lead to a longer investigation period as it actually would be).

Let's say, there is the following function in a contract:

    function doRevert() public {
        revert("Hallo");
    }

When running the following test (pls consider "Hello" vs "Hallo"):

`expect(instance.doRevert()).to.be.revertedWith('Hello');`

it will not get catched this way, instead:

> expected: 'Transaction reverted with Hello.'

> AssertionError: Expected transaction to be reverted with Hello., but other exception was thrown: Error: VM Exception while processing transaction: reverted with reason string 'Hallo'] {

When I add a dot into my message:

    function doRevert() public {
        revert("Hallo.");
    }

I will receive the following error message:

> expected: 'Transaction reverted with Hello..'
> AssertionError: Expected transaction to be reverted with Hello.., but other exception was thrown: Error: VM Exception while processing transaction: reverted with reason string 'Hallo.'] {

**Comment by rzadp** [comment]
@itinance I was not able to reproduce this on newest Waffle version `4.0.2`.
Feel free to reopen if it's still appending the dot on version 4.
