### ISSUE TITLE
Allowing multiple return values for a mock method

### ISSUE THREAD

**Issue by davidfragalaureano** [TrueFiEng/Waffle#714]
Following the example for `mockito` in Java:

```java
when(mockFoo.someMethod())
        .thenReturn(obj1)
        .thenThrow(new IllegalArgumentException())
        .thenReturn(obj2, obj3);
```

Is it possible to have a feature that lets us return different values each time a mock method is called?

Perhaps something that can be chained as above:

```ts
await mockContract.mock.someMethod
            .returns(someValue)
            .reverts()
            .returns(someOtherValue)
```

So the first `returns` is called when the mock method is called for the 1st time, the `reverts` the second time and so on.

**Comment by pawelpolak2** [comment]
Implemented in #816
