### ISSUE TITLE
Mocking contract at specific address

### ISSUE THREAD

**Issue by lukehutch** [TrueFiEng/Waffle#729]
Some EIPs define that contracts must be [deployed at specific addresses](https://eips.ethereum.org/EIPS/eip-1820). How can I call `deployMockContract` while specifying the address to deploy the mocked contract at? (I can't find a way using the current API.)

Relatedly, how can I determine if there is already a contract deployed at a given address (to avoid re-deployment)?

(Related, for another mocking framework: https://github.com/defi-wonderland/smock/issues/47)

**Comment by rzadp** [comment]
Interesting, we'll look into it and see if we can implement it.
External contributions are welcome as well.

**Comment by joelamouche** [comment]
I need that too to simulate an Optimism bridge. I would settle for a way to impersonate an account on ganache too.

>External contributions are welcome as well.

happy to help if you point me in the right direction
