### ISSUE TITLE
getWallets() generates the same wallets regardless of ganacheOptions

### ISSUE THREAD

**Issue by cNoveron** [TrueFiEng/Waffle#737]
Hey guys,

Just wanted to tell you I lost an awkwardly innumerable amount of hours trying to get MockProvider to do something very simple:
**Creating more than 10 funded wallets**

At first I was using Waffle 3.4.0. I noticed that following the docs to the letter wouldn't work:
```javascript
let ganacheOptions = {
    total_accounts: 100,
}
const provider = new MockProvider({ ganacheOptions })
const wallets = provider.getWallets()
```
So I migrated to Waffle 4.0.0 (updating the necessary dependencies of course), and made the proper changes to `ganacheOptions` as thoroughly docummented by means of a link to Ganache code GitHub:
```javascript
let ganacheOptions = {
    wallet: {
         totalAccounts: 100,
    }
}
const provider = new MockProvider({ ganacheOptions })
const wallets = provider.getWallets()
```
Which [you guessed it] didn't change the behavior of MockProvider whatsoever, because MockProvider would just create the 10 default accounts... But then I tried:
```javascript
const accounts = Array(100).fill({ balance: '0xff' })
let ganacheOptions = {
  wallet: {
    accounts,
    defaultBalance: 100,
  },
}
```
Which would yield the following error:
```
/home/.../node_modules/ethers/node_modules/@ethersproject/bytes/src.ts/index.ts:58
    return !!(value.toHexString);
                    ^
TypeError: Cannot read property 'toHexString' of undefined
    at isHexable (/home/.../node_modules/ethers/node_modules/@ethersproject/bytes/src.ts/index.ts:58:21)
```
Fantastic! That's some progress right?....

Ended up adventuring all the way into the woods: I read through the unbundled code and added logs to several lines. That made me realize the docs were a lie all this time! This is the implementation for `getWallets()`:
```javascript
    getWallets() {
        var _a, _b, _c;
        const items = (_c = (_b = (_a = this.options) === null || _a === void 0 ? void 0 : _a.ganacheOptions.wallet) === null || _b === void 0 ? void 0 : _b.accounts) !== null && _c !== void 0 ? _c : defaultAccounts_1.defaultAccounts;
        return items.map((x) => new ethers_1.Wallet(x.secretKey, this));
    }
```
First point: WHY?
Second: This piece of code will NEVER generate accounts either from a seed, or a mnemonic, or anything whatsoever. Nedless to say, passing options object with a config that tells the damn thing to create whatever number of accounts will be utterly and epicly ignored. [Someone had previously talked about this but just addressed the case of the mnemonic](https://github.com/TrueFiEng/Waffle/issues/404).

At this point I contemplated pivoting my career into content-writing or something like that, but then I remembered the fact that Waffle's MockProvider was just a wrapper for Ganache provider, and I could in fact cut the corner and instantiate Ganache provider myself [Thank you very much Waffle]:
```javascript
const accounts = Array(100).fill({ balance: '0xff' })
let ganacheOptions = {
  wallet: {
    accounts,
  },
}
const ga = ganache.provider(ganacheOptions).getInitialAccounts()
const wallets = ga.map(x => new Wallet(x.secretKey))
```
I though Waffle was supposed to take complexity out of using Ganache directly, but it looks like we're all better of just diching MockProvider and using Ganache directly to generate the wallets.

Just FYI

**Comment by rzadp** [comment]
Hey @cNoveron,
I'm sorry you had a hard time with this, and thank you for the detailed writeup.
I have pushed a fix in https://github.com/TrueFiEng/Waffle/pull/770 with missing tests for `getWallets()` against different `ganacheOptions.wallet` config.
