### ISSUE TITLE
`.not.be.reverted` matcher invalidates any prior `.to.emit` matchers

### ISSUE THREAD

**Issue by rslobodian** [TrueFiEng/Waffle#747]
Example of a test that should fail but passes:

![image](https://user-images.githubusercontent.com/8525665/174463460-b3e7e584-f670-49bd-be27-e83cd53d2bd2.png)
![image](https://user-images.githubusercontent.com/8525665/174463467-4a3c30a4-bf24-4af8-88ed-21e749f9a593.png)

it should be obvious but in my example above `some inexistent event` is not a valid event that my contract throws. By appending the `.and.not.be.reverted` matcher it seems like it completely invalidates the prior `emit` matcher.

If I remove the `and.not.be.reverted` from that test, I get the expected test failure.

**Comment by rzadp** [comment]
@rslobodian Thanks for the report, which version of Waffle do you have, and are you using Ganache or Hardhat with it?

**Comment by rzadp** [comment]
@rslobodian We have an alpha version of Waffle 4, where we try to nail down those issues.
You might want to try out the `@alpha` tag.

**Comment by rslobodian** [comment]
Do you guys have an ETA on when the RC of v4 will come out? I'd prefer not to use the alpha.

**Comment by rzadp** [comment]
> Do you guys have an ETA on when the RC of v4 will come out? I'd prefer not to use the alpha.

Don't want to make promises, but I'm thinking next month.

**Comment by rzadp** [comment]
Waffle version 4 is out 🎉
