### ISSUE TITLE
Cannot check that an event was emitted if the event was declared in a library.

### ISSUE THREAD

**Issue by hickscorp** [TrueFiEng/Waffle#754]
Note that this report is similar to the one at https://github.com/projectsophon/hardhat-diamond-abi/issues/16.

When developing smart contracts using the Diamond pattern, very often several facets of the same Diamond need to emit the same event.
Usually, events are declared in a library - such as `MyDiamondEvents`. Then in any facets, you can `emit MyDiamondsEvents.SomeEvent(...)'.

Waffle doesn't allow to check that an such event was emitted - because the types and ABI of the facet won't contain any information about the event typings.

**Comment by rzadp** [comment]
Please take a look again at https://ethereum-waffle.readthedocs.io/en/latest/matchers.html#emitting-events
(It was just added so you might not have seen it before).

<img width="1013" alt="Screenshot 2022-07-29 at 15 52 05" src="https://user-images.githubusercontent.com/12039224/181774970-1a4bc147-1a7b-4505-a1e4-566fbe44b3d5.png">

Feel free to open with more details if this does not work for you.
