### ISSUE TITLE
revertedWith().withArgs fails for uint values exceeding JavaScript's max int limit

### ISSUE THREAD

**Issue by iconofsin** [TrueFiEng/Waffle#785]
**Describe the bug**

Capturing a `revertsWith('customError').withArgs(n)` where `n` is a BigNumber too large to be consumed by `BigNumber.from` as an integer (vs as a string, which would work) fails conversion and results in the following BigNumber error:

```
Error: overflow [ See: https://links.ethers.org/v5-errors-NUMERIC_FAULT-overflow ] (fault="overflow", operation="BigNumber.from", value=1000000000000000000, code=NUMERIC_FAULT, version=bignumber/5.6.0)
```

**To Reproduce**
1. clone https://github.com/iconofsin/Waffle-revertsWith-withArgs-Overflow 
2. run `yarn install`
3. run `npx hardhat test`

**Software versions**
- `ethereum-waffle` 4.0.2
- `@nomiclabs/hardhat-waffle` 2.0.3
- `hardhat` 2.10.1
 - Package manager: yarn 1.22.10
 - Node version v16.3.0
- Solidity version: > 0.8.4

**Additional context**
As a dirty workaround, I patched `decodeHardhatError` in `waffle-chai/src/matchers/revertedWith.ts`.
L68
```
context.args = [JSON.parse(`[${matches[2]}]`)];
```
->

```
context.args = [JSON.parse(`[${matches[2].replace(/(\b\d{15,}\b)/g, '"$1"')}]`)];
```

which essentially quotes any potential BigNumber.

This results in matcher working, but it's obviously not the way to solve the issue.

**Comment by rzadp** [comment]
@iconofsin Do you have `@nomiclabs/hardhat-ethers` installed? What is it's version?

I added a test for it: https://github.com/TrueFiEng/Waffle/pull/786
Which shows that the matcher works fine for:
- `hardhat@2.10.1`
- `@nomiclabs/hardhat-ethers@2.1.0`
- `@nomiclabs/hardhat-waffle@2.0.3`

And fails (your error reproduced) for:
- `hardhat@2.9.2`
- `@nomiclabs/hardhat-ethers@2.0.3`
- `@nomiclabs/hardhat-waffle@2.0.3`

But I have not been able to reproduce the error with `hardhat@2.10.1`, even with `@nomiclabs/hardhat-ethers@2.0.3`.

**Comment by iconofsin** [comment]
Per my `package.json`, the versions of these packages are as follows:
```
  "@nomiclabs/hardhat-ethers": "^2.1.0",
  "@nomiclabs/hardhat-waffle": "^2.0.3",
  "hardhat": "^2.10.1"
  ```
